/*                        
________________________________________________________________________________
                            "Password Manager"  
################################################################################
[*]Graphical User Interface
[*]creator:Alexander M. Sapo
[*]https://github.com/conan0s4
[*]alexandermsapo@gmail.com
[*]BSIT 1st Year Finals project

note: serves as foundations
[#] basic understanding of cryptography (encryption & decryption)
 |___--> both for:
      * OpSec  (proper security practices) 
[#] secure management of psw credentials 
      * Malware Dev (Payload obfuscation / evasion )
[#]Basic (system) tool CLI commnad line interface  || GUI
_______________________________________________________________________________
functionalities:
################################################################################
--> https://app.milanote.com/1UawBQ1ueFnFXg/home
note: I REMOVED THE ENCRYPTION/DECRYPTION FUNCTIONALITY (must have this function!)
reason: it's causing an error which i don't get so due to limited time we will put iit aside for
now 
________________________________________________________________________________
*/
/* w/ Documentation:
################################################################################
*/
package password.manager.main;

import java.sql.*;


public class PasswordManagerUI extends javax.swing.JFrame {


    
 ///////////////////////////////////////////////////////////////////////////////////////////////    
    public PasswordManagerUI() {
        initComponents();
        setLocationRelativeTo(null); //center window ui
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableoutput = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        txtuser = new javax.swing.JTextField();
        txtplat = new javax.swing.JTextField();
        prompt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        generate = new javax.swing.JButton();
        iddelete = new javax.swing.JTextField();
        pgenerate = new javax.swing.JTextField();
        view = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableoutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Password", "Platform"
            }
        ));
        jScrollPane1.setViewportView(tableoutput);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setText("Platform");

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });

        txtplat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplatActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Password Manager");

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        generate.setText("generate");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        pgenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgenerateActionPerformed(evt);
            }
        });

        view.setText("view");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(prompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(save))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pgenerate, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(9, 9, 9)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(16, 16, 16)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtplat)
                                    .addComponent(txtuser)
                                    .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iddelete, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtplat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save)
                            .addComponent(view))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generate)
                            .addComponent(pgenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete)
                    .addComponent(iddelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtplatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplatActionPerformed
 
    private void pgenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgenerateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgenerateActionPerformed

 ///////////////////////////////////////////////////////////////////////////////////////////////      
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
   
 //get user input from input fields
    String platform = txtplat.getText();
    String username = txtuser.getText();
    String password = new String(txtpass.getPassword()); //(user will have  to reinput again his pass if not strong)
        
//check if password strong        
SecurePasswordRule checker = new SecurePasswordRule();  //from securepasswordrule class (instintiation)
if (!checker.isPasswordStrong(password)) { //if not strong then prompt user (if returned false)
    prompt.setText("Password not strong enough!");
    txtpass.setText("");// clears the txtpass field
    return; //does not proceed (stops) 
}
///////////////////////////////////////////////////    
  // Save to DB (saving process) --> handler
    SQLITEDataBaseHandler dbHandler = new SQLITEDataBaseHandler(); //class instansiation
    boolean success = dbHandler.savePasswordEntry(username, password, platform); //call method (true/false)
    //uses the handler class specifically the savepassentry method

    if (success) { //if success prompt user
        prompt.setText("Password saved successfully.");
        //Clear input fields
        txtuser.setText("");
        txtpass.setText("");
        txtplat.setText("");
    } else { //not failed prompt user
        prompt.setText("Failed to save password.");
    }  


        
        
        
        
    }//GEN-LAST:event_saveActionPerformed
////////////////////////////////////////////////////////////////////////////////
    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
//SECURE || STRONG PASSWORD GENERATOR
PasswordGenerator generator = new PasswordGenerator(); //class instatiation
String newPass = generator.generate(); //generate method called
pgenerate.setText(newPass);//(pgenerate field) set text to the results from (newpass)--> .generate method 
    }//GEN-LAST:event_generateActionPerformed
//generate method will return a randomly generated pass that follows the strong pass rule we made for the generator
////////////////////////////////////////////////////////////////////////////////    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
     
     //get user inputs (id)   
    String idStr = iddelete.getText();
    if (idStr.isEmpty()) { //check if id isempty --> if empty prompt user
        prompt.setText("Please enter an ID to delete.");
        return;
    }

    try { //convert id string to int
        int id = Integer.parseInt(idStr);
        SQLITEDataBaseHandler dbHandler = new SQLITEDataBaseHandler(); //dbhandler class instatiation   
        boolean success = dbHandler.deletePasswordEntry(id); //delete the (user,pass,platform) group  by its id 

        if (success) { //ifsuccess prompt user
            prompt.setText("Entry deleted successfully.");
            iddelete.setText("");
        } else { //ifnot then prompt user
            prompt.setText("Entry not found or failed to delete.");
        }
    } catch (NumberFormatException e) { //handles non-integer inputs (invalid id formats)
        prompt.setText("Invalid ID format.");
    }







    }//GEN-LAST:event_deleteActionPerformed

    
    
    
    
////////////////////////////////////////////////////////////////////////////////-----> event listener (buttons)    
    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
   
 
        
    SQLITEDataBaseHandler dbHandler = new SQLITEDataBaseHandler(); //class instatiation
    ResultSet rs = dbHandler.viewPasswordEntries(); 
    //calls a method viewPasswordEntries --> returns  ResultSet containing rows from your password table.
    
    
    
    //prepares table for new data------>
    try { //gets the structure of the outputtable --> cast to defualt table model to add rows
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableoutput.getModel();//---> make modl editable
//                                   identifier --> assign-->convert to editable-->identifier of the table in gui-->get tables data        
        model.setRowCount(0); // Clear previous rows or existing (old) data before adding a new row
        //(prevents duplication  every time view button is clicked)

        
        
        while (rs.next()) { //loop through each row in the resualtset
            // Get data from each column of the current row
            int id = rs.getInt("id"); //get (id,user,psw,plat)
            String user = rs.getString("user"); 
            String pass = rs.getString("password");
            String plat = rs.getString("platform");
 
            model.addRow(new Object[]{id, user, pass, plat}); //Adds a new row to the (here) table using the values retrieved from the database.
        } /*Extracts ID, username, password, and platform from each DB row/adds each entry as a new row in the table.*/
        prompt.setText("Entries loaded."); //prompts user if entry was loadedsuccessfully 
    } catch (SQLException e) {
        prompt.setText("Error loading entries."); //error handling
        e.printStackTrace();
    }     
        
        
        
        
    }//GEN-LAST:event_viewActionPerformed

    
    
    
    
    
    
    
    
    
    
    
 ///////////////////////////////////////////////////////////////////////////////////////////////    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordManagerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton generate;
    private javax.swing.JTextField iddelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pgenerate;
    private javax.swing.JLabel prompt;
    private javax.swing.JButton save;
    private javax.swing.JTable tableoutput;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtplat;
    private javax.swing.JTextField txtuser;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
